{% set name = "pytest-server-fixtures" %}
{% set version = "1.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest-server-fixtures-{{ version }}.tar.gz
  sha256: 3d02893dced1ea8d1490a2f8dafcbf4c291bca002ddc375c7b29039745b99fdd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7|>=3.4
    - setuptools-git
  run:
    - future
    - psutil
    - pytest
    - pytest-fixture-config
    - pytest-shutil
    - python >=2.7|>=3.4
    - requests
    - retry
    - six

test:
  imports:
    - pytest_server_fixtures
    - pytest_server_fixtures.serverclass

about:
  home: https://github.com/manahl/pytest-plugins
  summary: Extensible server fixures for py.test
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
