{% set name = "pytest-server-fixtures" %}
{% set version = "1.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-server-fixtures-{{ version }}.tar.gz
  sha256: c5e733d20a8d0e773ca513e360e4ba2647952ea9428fa2bd05516c6281ea3ce7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7|>=3.4
    - setuptools-git
  run:
    - future
    - psutil
    - pytest
    - pytest-fixture-config
    - pytest-shutil
    - python >=2.7|>=3.4
    - requests
    - retry
    - six

test:
  imports:
    - pytest_server_fixtures
    - pytest_server_fixtures.serverclass

about:
  home: https://github.com/manahl/pytest-plugins
  summary: Extensible server fixures for py.test
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
